EGMovies.WebUI/ViewModels/CinemaDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using EGMovies.BOL;

namespace EGMovies.WebUI.ViewModels
{
    public class CinemaDetailsViewModel
    {
        public Cinema Cinema { get; set; }
        public CinemaGroup  CinemaGroup { get; set; }
        public List<Show> Shows { get; set; }
        public List<Movie> Movies { get; set; }
      
            
    }
}

EGMovies.WebUI/ViewModels/MovieDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EGMovies.BOL;


namespace EGMovies.WebUI.ViewModels
{
    public class MovieDetailsViewModel
    {
        public Movie Movie { get; set; }
        public List<Actor>  Actors { get; set; }
        public List<Show> Shows { get; set; }
        public List<Cinema>  Cinemas { get; set; }

    }
}

EGMovies.WebUI/Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EGMovies.BOL;
using EGMovies.DAL;
using EGMovies.WebUI.ViewModels;

namespace EGMovies.WebUI.Controllers
{
    public class AreasController : Controller
    {
        // GET: Areas
        public ActionResult Index(string id)
        {
            CinemaGroupRepository repoCinemaGroup = new CinemaGroupRepository();

            ViewBag.id = new SelectList(repoCinemaGroup.GitAreas());



            CinemaRepository repoCinema = new CinemaRepository();

            if (!string.IsNullOrEmpty(id))
            {
                return View(repoCinema.GitCinemasByAreaName(id));
            }
            else
            {
                return View(repoCinema.GitAll());
            }

        }


        public ActionResult Details(int id)
        {
            CinemaRepository repoCinema = new CinemaRepository();
            Cinema cinema = repoCinema.GitCinemaByCinemaId(id);
            CinemaGroup cinemaGroup = repoCinema.GitCinemaGroupByCinemaId(id);
            List<Show> shows = repoCinema.GitShowsByCinemaId(id);

            CinemaDetailsViewModel cinemaDetailsViewModel = new CinemaDetailsViewModel
            {
                Cinema = cinema,
                CinemaGroup = cinemaGroup,
                Shows = shows
            };

            return View(cinemaDetailsViewModel);
        }


    }
}

EGMovies.WebUI/Controllers/CinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EGMovies.DAL;
using EGMovies.BOL;
using EGMovies.WebUI.ViewModels;

namespace EGMovies.WebUI.Controllers
{
    public class CinemaController : Controller
    {
        // GET: Cinema
       
        public ActionResult Index(string id)
        {
            int CinemaGroupId = 0;
            CinemaGroupRepository repoCinemaGroup = new CinemaGroupRepository();

            ViewBag.id = new SelectList(repoCinemaGroup.GitAll(), "Id", "Name");
            CinemaRepository repoCinema = new CinemaRepository();

            if (!string.IsNullOrEmpty(id))
            {
                int.TryParse(id, out CinemaGroupId);
            }
            else
            {
                int.TryParse(id, out CinemaGroupId);

            }

            if (CinemaGroupId >0 )
            {
                return View(repoCinema.GitCinemasByCinemaGroup(CinemaGroupId));
            }
            else
            {
                return View(repoCinema.GitAll());

            }


        }

        public ActionResult Details(int id)
        {
            CinemaRepository repoCinema = new CinemaRepository();
            Cinema cinema = repoCinema.GitCinemaByCinemaId(id);
            CinemaGroup cinemaGroup = repoCinema.GitCinemaGroupByCinemaId(id);
            List<Show> shows = repoCinema.GitShowsByCinemaId(id);

            CinemaDetailsViewModel cinemaDetailsViewModel  = new CinemaDetailsViewModel
            {
                Cinema = cinema ,
                CinemaGroup = cinemaGroup ,
                Shows =shows
            };

            return View(cinemaDetailsViewModel);
        }
    }
}

EGMovies.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EGMovies.BOL;
using EGMovies.DAL;
using EGMovies.WebUI.ViewModels;


namespace EGMovies.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index(string id)
        {
            MovieRepository repoMovie = new MovieRepository();
            if (!string.IsNullOrEmpty(id))
            {
                return View(repoMovie.SearchByMovieName(id));
            }
            else
            {
                return View(repoMovie.GitAll());

            }
        }

        public ActionResult Details(int id)
        {
            MovieRepository repoMovie = new MovieRepository();
            Movie movie = repoMovie.GitMovieByMovieId(id);
            List<Actor> actors = repoMovie.GitActorsByMovieId(id);
            List<Show> shows = repoMovie.GitShowsByMovieId(id);
            List<Cinema> cinemas = repoMovie.GitCinemasByMovieId(id);

            MovieDetailsViewModel movieDetailsViewModel = new MovieDetailsViewModel
            {
                Movie = movie,
                Actors = actors,
                Shows = shows,
                Cinemas = cinemas
            };

            return View(movieDetailsViewModel);

        }

        public ActionResult ByMovieGenre(string moviegenre)
        {
            MovieRepository repoMovie = new MovieRepository();


            ViewBag.movieGenre = new SelectList(repoMovie.GitGenres());
            repoMovie = new MovieRepository();

            if (!string.IsNullOrEmpty(moviegenre))
            {
                return View(repoMovie.GitMoviesByGenre(moviegenre));
            }
            else
            {
                return View(repoMovie.GitAll());

            }
            
        }

    }
}

EGMovies.WebUI/Views/Areas/Details.cshtml
@model EGMovies.WebUI.ViewModels.CinemaDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CinemaDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cinema.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cinema.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup .Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Description )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Telephone)
        </dd>

       


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Shows)
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.Actors)
                    </th>*@

            </tr>

            @foreach (var item in Model.Shows)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Movie.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Movie.ShowingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShowFrom)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ShowTo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cinema.Name)
                    </td>

                </tr>
            }

        </table>


    </dl>


</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

EGMovies.WebUI/Views/Areas/Index.cshtml
@model IEnumerable<EGMovies.BOL.Cinema>

@{
    ViewBag.Title = "Search By Area Name";
}

<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@


    @using (Html.BeginForm("Index", "Areas", FormMethod.Get))
    {
        <div>
            <table>
                <tr>
                    <td><label> Search By Area Name : </label></td>
                    <td>@Html.DropDownList("id", "All")</td>
                    <td><input type="submit" value="Search" /></td>

                </tr>
            </table>
        </div>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CinemaGroupId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CinemaGroup.Name)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
        </td>
    </tr>
}

</table>

EGMovies.WebUI/Views/Cinema/Details.cshtml
@model EGMovies.WebUI.ViewModels.CinemaDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CinemaDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cinema.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cinema.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup .Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Description )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CinemaGroup.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CinemaGroup.Telephone)
        </dd>

       


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Shows)
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.Actors)
                    </th>*@

            </tr>

            @foreach (var item in Model.Shows)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Movie.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Movie.ShowingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShowFrom)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ShowTo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cinema.Name)
                    </td>

                </tr>
            }

        </table>


    </dl>


</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

EGMovies.WebUI/Views/Cinema/Index.cshtml
@model IEnumerable<EGMovies.BOL.Cinema>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>

    @using (Html.BeginForm("Index", "Cinema", FormMethod.Get))
    {
    <p>
        Cinema Group: @Html.DropDownList("id", "All")

        <input type="submit" value="Search" />
    </p>
    }



    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CinemaGroupId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CinemaGroup.Name)
                </td>
                <td>

                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

EGMovies.WebUI/Views/Home/ByMovieGenre.cshtml
@model IEnumerable<EGMovies.BOL.Movie>

@{
    ViewBag.Title = "Search By Movie Genre";
}

<h2>ByMovieGenre</h2>
<p>
    @using (Html.BeginForm("ByMovieGenre", "Home", FormMethod.Get))
    {
        <div>
            <table>
                <tr>
                    <td><label>Search By Movie Genre: </label></td>
                    <td>@Html.DropDownList("movieGenre", "All")</td>
                    <td><input type="submit" value="Search" /></td>

                </tr>
            </table>
        </div>
    }

    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShowingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShowingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new {id = item.Id})

        </td>
    </tr>
}

</table>

EGMovies.WebUI/Views/Home/Details.cshtml
@model EGMovies.WebUI.ViewModels.MovieDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>


<div>
    <h4>MovieDetailsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Movie.Name )
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie.ShowingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.ShowingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.Description)
        </dd>


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Actors)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Actors)
                </th>*@
                
            </tr>

            @foreach (var item in Model.Actors )
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role)
                    </td>
                    
                </tr>
            }

        </table>


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Shows)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Actors)
                </th>*@

            </tr>

            @foreach (var item in Model.Shows)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cinema.Name )
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShowFrom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShowTo)
                    </td>

                </tr>
            }

        </table>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cinemas)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Actors)
                </th>*@

            </tr>

            @foreach (var item in Model.Cinemas)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CinemaGroup.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>

                </tr>
            }

        </table>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EGMovies.WebUI/Views/Home/Index.cshtml
@model IEnumerable<EGMovies.BOL.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "Home", FormMethod.Get))
{
    <div>
        <table>
            <tr>
                <td><label>Search By Movie Name :</label></td>
                <td>@Html.TextBox("id")</td>
                <td><input type="submit" value="Search"/></td>

            </tr>
        </table>
    </div>
}
<p>
    @*@Html.ActionLink("Create New", "Create")*@
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShowingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShowingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.id }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
            @*| @Html.ActionLink("Delete", "Delete", new { id=item.id })*@
        </td>
    </tr>
}

</table>

EGMovies.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> @Html.ActionLink("Search By Movie Genure", "ByMovieGenre", "Home") </li>
                    <li> @Html.ActionLink("Search By Cinema Gropup", "Index", "Cinema") </li>
                    <li> @Html.ActionLink("Search By Area", "Index", "Areas") </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>